name: Create Release with Build Asset

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
      # Step 1: Checkout the repository code
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci

      # Step 2: Build the project
      - name: Build project
        run: npm run build
      
      # Step 3: Get the version number
      - name: Get package info
        id: package
        uses: codex-team/action-nodejs-package-info@v1.1

      # Step 3: Create a release
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package.outputs.version }}
          release_name: ${{ steps.package.outputs.version }}
          body: Automated release created by GitHub Actions
          draft: false
          prerelease: false
      
      # Step 4: Compress files
      - name: Compress files
        run: zip -r release.zip .next server.js package.json node_modules public

      # Step 5: Upload build artifacts as release assets
      - name: Upload release assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: garage-${{ steps.package.outputs.version }}.zip
          asset_content_type: application/zip
