name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
      # Step 1: Checkout the repository code
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci

      # Step 2: Build the project
      - name: Build project
        run: npm run build

      # Step 3: Create a release
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Automated release created by GitHub Actions
          draft: false
          prerelease: false

      # Step 4: Upload build artifacts as release assets
      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: raspberry-pi-4-build
          path: /garage-door-next/garage-door-next/.next/ | /garage-door-next/garage-door-next/server.js
